backend:
  name: git-gateway
  branch: main

# Remove the auth section since we're handling it manually
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - label: "Main Profile"
        name: "profile"
        file: "src/data/profile.json"
        fields:
          - label: "Artist Name"
            name: "artistName"
            widget: "string"
            default: "TumblysArt"
            
          - label: "Profile Image"
            name: "profileImage"
            widget: "image"
            default: "/JumpingForJoy.png"
            
          - label: "Navigation Buttons"
            name: "buttons"
            widget: "list"
            min: 1
            max: 6
            fields:
              - label: "Button Text"
                name: "text"
                widget: "string"
                
              - label: "Link Destination" 
                name: "url"
                widget: "string"
                
              - label: "Button Color"
                name: "color"
                widget: "select"
                default: "white"
                options:
                  - { label: "White", value: "white" }
                  - { label: "Purple", value: "purple" }
                  - { label: "Pink", value: "pink" }
                  - { label: "Blue", value: "blue" }
                  - { label: "Green", value: "green" }
                
              - label: "Text Color"
                name: "textColor"
                widget: "select"
                default: "black"
                options:
                  - { label: "Black", value: "black" }
                  - { label: "White", value: "white" }
                  - { label: "Gray", value: "gray" }